theme:
  name: material
  palette:
    scheme: slate
site_name: JuryMindAi
site_url: https://www.jurymindai.com

nav:
  - API Documentation:
      - api.md
      # - prompts.md
      # - pipelines.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [jurymind]

      
