theme:
  name: material
site_name: JuryMindAi
site_url: https://www.jurymindai.com

nav:
  - API Documentation:
      - core.md
      - prompts.md
      - pipelines.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [jurymind]
